"""Static content for the shared report; all rows are readable without JavaScript."""
import html,json
from pathlib import Path
def section():
    d=json.loads((Path(__file__).parent/'dist/mooch_data.json').read_text())
    esc=lambda x:html.escape(str(x or ''))
    def val(x):return '—' if x is None else f'{x:g}'.replace('.',',')
    rows=[]
    for r in d['combined']:
        cells=[esc(r['model']),val(r.get('rated_mAh')),val(r.get('tested_mAh')),val(r.get('estimated_CDR_A')),val(r.get('estimated_TL_A')),val(r.get('DCIR_mOhm'))]+[val(r.get('E'+str(a)+'_Wh')) for a in [5,10,15,20,30,40,50]]
        cells += [esc(r.get('test_date') or ('Публикация '+r.get('publication_date',''))),esc(r['source_kind'])+('<br><a target="_blank" rel="noopener" href="'+esc(r['url'])+'">Статья ↗</a>' if r.get('url') else ''),esc(r.get('note'))]
        rows.append('<tr>'+''.join('<td>'+x+'</td>' for x in cells)+'</tr>')
    return '''<section class="section" id="mooch"><div class="wrap"><p class="eyebrow">Обновлено 20 сентября 2026 · Battery Mooch</p><h2>Испытания 21700.<br>Ёмкость больше 4 А·ч.</h2>
<p>41 строка с вашей таблицы от 11.08.2026 и два новых теста: Linkdata 50T и Great Power 60Q. Дополнительно сохранён реестр 39 тем форума; текст прочитан у шести. Полный архив не выгружен: форум потребовал CAPTCHA.</p>
<div class="toolbar"><div class="field wide"><label for="mooch-search">Модель или производитель</label><input id="mooch-search" type="search" placeholder="Например, Tenpower"></div><div class="field"><label for="mooch-current">Оценка CDR не ниже</label><select id="mooch-current"><option value="0">Любой ток</option><option value="20">20 А</option><option value="30">30 А</option><option value="40">40 А</option></select></div><div class="field"><label for="mooch-sort">Сортировка</label><select id="mooch-sort"><option value="name">По модели</option><option value="E20_Wh">Энергия при 20 А</option><option value="E30_Wh">Энергия при 30 А</option><option value="DCIR_mOhm">DCIR, по возрастанию</option><option value="estimated_CDR_A">Оценка CDR</option></select></div></div>
<p class="download-links"><a class="pill" href="Mooch_21700_2026-09-20.xlsx">Excel: фото и форум</a> <a href="mooch_21700_comparison.csv">CSV сравнения</a> · <a href="mooch_21700_forum.csv">CSV форума</a> · <a href="mooch_21700_photo.csv">CSV фото</a> · <a href="assets/mooch-21700-2026-08-11.jpeg">Исходное фото</a> · <a href="https://www.e-cigarette-forum.com/forums/batteries-and-chargers.828/" target="_blank" rel="noopener">Первоисточник ↗</a></p>
<div class="callout"><strong>CDR и TL — разные режимы.</strong> CDR — оценка непрерывного тока Mooch. TL допускает более высокий ток только с температурной отсечкой. Энергия E-Score измерена до 2,80 В; наличие результата при токе выше CDR не разрешает длительную работу на таком токе. Прочерк означает отсутствие данных.</div>
<p id="mooch-count" class="note" aria-live="polite">43 записи</p><div class="table-wrap" tabindex="0" role="region" aria-label="Испытания 21700, горизонтальная прокрутка"><table id="mooch-table"><thead><tr>'''+''.join('<th scope="col">'+h+'</th>' for h in ['Модель / версия','Rated, мА·ч','Tested, мА·ч','CDR Mooch, А','TL Mooch, А','DCIR, мОм','5 А, Вт·ч','10 А, Вт·ч','15 А, Вт·ч','20 А, Вт·ч','30 А, Вт·ч','40 А, Вт·ч','50 А, Вт·ч','Дата теста / публикации','Источник','Условия / замечания'])+'''</tr></thead><tbody id="mooch-body">'''+''.join(rows)+'''</tbody></table></div>
<details class="mooch-notes"><summary>Как читать данные и расхождения</summary><p>Rated и Tested с фото сохранены буквально; точные ёмкости отдельных образцов находятся на листе «Форум». Даты испытания и публикации раздельны. В фото у RS50 G3E DCIR 6,5 мОм, тогда как прежний расчёт опирается на другой результат 5,54 мОм. Спорная строка Samsung 58E/CC4593F101 не объединена с найденной статьёй о 55E/CC5493F101.</p><p>LG H50 включён по измеренной ёмкости: паспортная неизвестна. Ячейки ровно 4 А·ч исключены. LG H51 и H51T, Samsung 50S и 50S2, предсерийные и CCC-версии различаются. DCIR Mooch при полном заряде не подменяет паспортный DCIR при другом SOC. Таблица не подтверждает ресурс и нагрев закрытого блока.</p><p>Методика и охват сохранены в Excel. Пометка исходной таблицы: не распространять после 11.02.2027 без обновления. Формат 21700 не определяет точную химию катода — данные о составе необходимо брать из паспорта конкретной модели.</p></details></div></section>'''
